version: '3'
services:
  discovery:
    image: celeduc/microservice-docker-discovery-service:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
  api-gateway:
    image: celeduc/microservice-docker-api-gateway:0.0.1-SNAPSHOT
    ports:
      - 5000:5000
    depends_on:
      - discovery
  config:
    image: celeduc/microservice-docker-config:0.0.1-SNAPSHOT
    volumes:
      - ./config-data:/var/config-data
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
        -Dspring.cloud.config.server.native.searchLocations=/var/config-data
    depends_on:
      - discovery
    ports:
      - 8888:8888
  immo-service:
    image: celeduc/microservice-docker-immo-service:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
        -Dspring.profiles.active=production
    restart: on-failure
    depends_on:
      - discovery
      - config
    ports:
      - 8080:8080